-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, 
ROUND(c.DAILY_FEE * 30 * (100-p.DISCOUNT_RATE)/100) as FEE
FROM CAR_RENTAL_COMPANY_CAR as c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as h on c.CAR_ID = h.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p on c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01'
) AND p.DURATION_TYPE like '30%'
GROUP BY c.CAR_ID
HAVING c.CAR_TYPE IN ('세단', 'SUV')
AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
