-- 코드를 작성해주세요
SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS as d, SKILLCODES as s
where 1 = 1 
and (d.SKILL_CODE & s.CODE) > 0
and CATEGORY = 'Front End'
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID;